---
title: Short Paper
author:
  - name: Alice Anonymous
    email: alice@example.com
    affiliation: Some Institute of Technology
    footnote: Corresponding Author
  - name: Bob Security
    email: bob@example.com
    affiliation: Another University
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
  - code: Another University
    address: Department, Street, City, State, Zip
abstract: |
  This is the abstract.

  It consists of two paragraphs.
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: references.bib
link-citations: yes
---


American Economic Review Pointers:

* Do not use an "Introduction" heading. Begin your introductory material
before the first section heading.

* Avoid style markup (except sparingly for emphasis).

* Avoid using explicit vertical or horizontal space.

* Captions are short and go below figures but above tables.

* The tablenotes or figurenotes environments may be used below tables
or figures, respectively, as demonstrated below.

* If you have difficulties with the mathtime package, adjust the package
options appropriately for your platform. If you can't get it to work, just
remove the package or see our technical support document online (please
refer to the author instructions).

* If you are using an appendix, it goes last, after the bibliography.
Use regular section headings to make the appendix headings.

* If you are not using an appendix, you may delete the appendix command
and sample appendix section heading.

* Either the natbib package or the harvard package may be used with bibtex.
To include one of these packages, uncomment the appropriate usepackage command
above. Note: you can't use both packages at once or compile-time errors will result.
